# maintain v2 separate mocks dir
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase }}.go"
pkgname: mocks

template: testify
packages:
  github.com/opencloud-eu/opencloud/services/collaboration/pkg/connector:
    config:
      dir: mocks
    interfaces:
      ConnectorService: {}
      ContentConnectorService: {}
      FileConnectorService: {}
  github.com/opencloud-eu/opencloud/services/collaboration/pkg/locks:
    config:
      dir: mocks
    interfaces:
      LockParser: {}
  github.com/opencloud-eu/reva/v2/pkg/rgrpc/todo/pool:
    config:
      dir: mocks
    interfaces:
      Selectable:
        config:
          filename: gateway_selector.go
