# maintain v2 separate mocks dir
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase }}.go"
pkgname: mocks

template: testify
packages:
  github.com/opencloud-eu/opencloud/services/proxy/pkg/user/backend:
    interfaces:
      UserBackend: {}
  github.com/opencloud-eu/opencloud/services/proxy/pkg/userroles:
    interfaces:
      UserRoleAssigner: {}
