# maintain v2 separate mocks dir
dir: "{{.InterfaceDir}}/mocks"
structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase }}.go"
pkgname: mocks

template: testify
packages:
  github.com/opencloud-eu/opencloud/pkg/oidc:
    interfaces:
      OIDCClient: {}
